### ISSUE TITLE
Support breaking change via prefix

### ISSUE THREAD

**Issue by erichulburd** [crate-ci/git-conventional#39]
> BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with [MAJOR](http://semver.org/#summary) in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.

Ref: https://www.conventionalcommits.org/en/v1.0.0/#summary

It seems that this repo only supports the `BREAKING CHANGE: ` footer rather than the commit `prefix!:` format. Unsure if the best approach here is to set the `breaking_description` to the commit message if the `!` is in the prefix; I imagine that could lead to some repetitive changelogs. Perhaps better to just set a `breaking` bool on the commit.

**Comment by epage** [comment]
[`Commit::breaking`](https://docs.rs/git-conventional/latest/git_conventional/struct.Commit.html#method.breaking) is `true` if either `!` is used or `BREAKING CHANGE:`. [`Commit::breaking_description`](https://docs.rs/git-conventional/latest/git_conventional/struct.Commit.html#method.breaking_description) returns `None` if there isn't an explicit breaking description so that callers can choose what they want to use for it if `Commit::breaking` is `true`.

If you have a case where `Commit::breaking` isn't true with `!`, that would be a bug and we'd need a reproduction case to move forward.

**Comment by erichulburd** [comment]
At a glance, I'm not seeing the `!` check: https://github.com/crate-ci/git-conventional/blob/0b65ab644c6116fced8a59eef72f44ef09f89e8d/src/commit.rs#L46 . Will double check though...

**Comment by epage** [comment]
Oh, I was mistaken, we do set `breaking_description` when `!` is used and that is what causes `let breaking` to be true.

See https://github.com/crate-ci/git-conventional/blob/0b65ab644c6116fced8a59eef72f44ef09f89e8d/src/commit.rs#L38,L45

**Comment by erichulburd** [comment]
Ah there it is `breaking.then(|| description)`. Something else must be wrong with my git pipeline, not passing the right commit message to [knope](https://github.com/knope-dev/knope). Sorry about that and thanks for your response! Closing this.
